name: iot_bluetooth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  get: 4.6.1
  get_storage: ^2.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: GideonRoman
      fonts:
        - asset: assets/fonts/GideonRoman.ttf
